### ISSUE TITLE
Crash with Rogulike Dungeons

### ISSUE THREAD

**Issue by MCEventHorizon** [Team-RTG/1.9-Realistic-Terrain-Generation#102]
It doesn't happen without RTG so I think it has something to do with this mod.
Crashlog: http://pastebin.com/fCJCgndH

**Comment by topisani** [comment]
This is the known biome dictionary bug. No idea whats causing it, but i will investigate.

The duplicate reffers to #78

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#808
