### ISSUE TITLE
RTG and Vampirism issue

### ISSUE THREAD

**Issue by aldun** [Team-RTG/1.9-Realistic-Terrain-Generation#103]
##### Affected Mod Versions
- Forge:12.16.1.1892
- RTG: 2.0.0-alpha 1
- Vampirism: 1.0.0-alpha

##### Issue Description:

When joining a server the client crashes with the attached crash report, server remains unaffected. The client was only able to connect to the server after creating a single player world with RTG as the world type.

##### Extra Information:

http://pastebin.com/ZLGsAzQv

**Comment by topisani** [comment]
I didnt think of that - ill fix it

**Comment by aldun** [comment]
Just an update, I removed Vampirism from my pack and still the only way the client can connect to the server is to load a single player world first otherwise the client crashes.

**Comment by topisani** [comment]
yeah it has nothing to do with vampirism - but it is fixed since that PR. We will make a release as fast as possible
