### ISSUE TITLE
Alpha Performance Issues

### ISSUE THREAD

**Issue by whitestarx0312** [Team-RTG/1.9-Realistic-Terrain-Generation#104]
### Team-RTG Issue Report Template
-------
Before getting started, for the sake of everyone's sanity, be sure that you are opening an issue in the correct repository as there are separate repositories for RTG-1.7.10, RTG-1.8.9, and RTG-1.9, and please fill out this document in full, the best that you can.

(If you are using one or more of the fallowing, put a 'x' between the '[ ]'s, and supply the relevant version number)`
- [ ] I am using Cauldren - version:
- [ ] I am using Spigot - version:
- [ ] I am using Sponge/SpongeForge - version:
- [ ] I am using one or more of the above, but I am _NOT_ trying to load RTG as a plugin. (from the /plugin/ directory)

-------
- [x] I am using Optifine - version: OptiFine_1.9.0_HD_U_B2
- [ ] I am using Fastcraft - version:

-------
##### Affected Mod Versions
- Forge: forge-12.16.1.1887
- RTG: RTG-1.9-2.0.0-alpha.1.jar

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

BOP: BiomesOPlenty-1.9-4.0.2.2018-universal
##### Issue Description:

Upon updating to the new alpha I noticed that the time to generate and start a new world increased significantly by at least 20 seconds, and made me think that the game was going to crash although it eventually did load. 

Furthermore, I have encountered an issue when generating new chunks. The TPS of the single player world skyrockets and chunks stop loading, leaving the area full of empty spaces. This does not happen when tested with RTG 0.0.5.

##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Install the latest alpha RTG with recommended Forge/BOP (if it's applicable)
2. Start a new world to view the increased startup time.
3. Explore new chunks in the new world to see the chunk generation issue along. The TPS does drop when chunks stop loading, but I think this is normal as we are generating new chunks. The main bug is how chunks seem to hang on this newer version and some don't even generate, instead just leaving blank space.

##### Extra Information:
If my log is needed please let me know. There was no crash or anything weird going on besides the chunk hangs and increased startup time.

**Comment by topisani** [comment]
Yeah, this was pretty much expected. We have to run some performance checks to see where exactly the issue lies, and there are some optimizations in 1.7-0.8.0 that still have to be ported.  

For now i recomend pressing f3+a to reload chunks if some dont show up, and then give it some time on initial generation.

**Comment by srs-bsns** [comment]
Lets move all performance discussion to #131
