### ISSUE TITLE
RTG-1.9-2.0.0-alpha.1 crashes client on connect

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.9-Realistic-Terrain-Generation#105]
In https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/700 @kreezxil said

> both server and client are running 1.9 Forge build 1898

**Comment by ShadowDrakken** [comment]
This only happens with clients connecting to servers btw. It crashes with just "Getting Biome" as the error message

Single player works just dandy.

I'm not sure if it's related or not, but I did notice RTG on the server side complaining about a hundred times during loading that it couldn't find realistic BoP biomes. Makes me wonder if the client is loading the full biome list but the server isn't, meaning the biome IDs end up out of sync maybe?

**Comment by topisani** [comment]
That's just me who forgot to remove those messages when I changed the initialisation to happen on world load, so those are completely unrelated. This is part of the whole biome dictionary issue we are having

**Comment by topisani** [comment]
fixed since that PR
