### ISSUE TITLE
Crash when generating a world without RTG

### ISSUE THREAD

**Issue by MCEventHorizon** [Team-RTG/1.9-Realistic-Terrain-Generation#106]
Affected Mod Versions
- Forge:1898
- RTG: 1.9-2.0.0-alpha.1

Issue Description: If you want to generate a normal or BoP world with this mod installed, it will crash. Doesn't happen on every world.

Crashlog: http://pastebin.com/bTDVfWGF

**Comment by srs-bsns** [comment]
If you aren't going to use RTG, why load it at all?

**Comment by whichonespink44** [comment]
> If you aren't going to use RTG, why load it at all?

The biggest use case for this is when RTG is included in a public mod pack which gives the player the option to choose which world type he/she wants to use.

The 1.7.10 version of RTG used to crash in non-RTG worlds, so we added some world type checks in [various](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/21fc085129b00cf447bf24ed2fe85e2802fba5ce/src/main/java/rtg/event/EventManagerRTG.java#L79) [places](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/21fc085129b00cf447bf24ed2fe85e2802fba5ce/src/main/java/rtg/world/gen/structure/MapGenVillageRTG.java#L71), which seemed to do the trick. We probably just need to do the same here in the Ocean Monument code.

**Comment by srs-bsns** [comment]
> The biggest use case for this is when RTG is included in a public mod pack which gives the player the option to choose which world type he/she wants to use.

Even in that case, one should make that decision before creating a world, and not load unneeded mods and pollute their environment with unneeded classes. That's just asking for conflicts and is just bad practice.

Perhaps we could add in some checks to prevent issues like this with RTG, but care will have to be taken for cases like if someone wants to use, say,  Vanilla or BoP for Dim 0 (or whatever dim the server sends people to when joining), but wants to have RTG available for RFTools/Mystcraft dims.

**Comment by topisani** [comment]
> Even in that case, one should make that decision before creating a world, and not load unneeded mods and pollute their environment with unneeded classes. That's just asking for conflicts and is just bad practice.  
While that may be true, modpacks partly exist for people who cannot or just dont want to have to mess with any of that. So of cause RTG should just shut up in any world that isnt RTG.  
Anyway, the issue is, as pink already mentioned, the ocean monument code. It doesnt do said worldcheck, and it should. This should be an easy fix, but for now, you have to remove RTG if you want to use another world type, cause it will crash when it wants to generate an ocean monument.

**Comment by topisani** [comment]
fixed since #113
