### ISSUE TITLE
Ocean monuments not generating

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.9-Realistic-Terrain-Generation#11]
Cant seem to find one, even where they are supposed to be.

**Comment by topisani** [comment]
Could be biome repair related? does it touch deep oceans in any way?

**Comment by Zeno410** [comment]
It's not supposed to. If they're coming out "Deep Ocean" you should still be getting the monuments.

**Comment by topisani** [comment]
since #16  the guardians apear but there is no structure

**Comment by Zeno410** [comment]
Do you get villages?

**Comment by whichonespink44** [comment]
Villages, temples, and witch huts are generating fine... it's just ocean monuments & igloos that aren't.

We'll need to look at [MapGenScatteredFeatureRTG.java](https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/master/src/main/java/rtg/world/gen/structure/MapGenScatteredFeatureRTG.java) and [StructureOceanMonumentRTG.java](https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/master/src/main/java/rtg/world/gen/structure/StructureOceanMonumentRTG.java) and see where it's falling down.

**Comment by topisani** [comment]
I'm already working on the ocean monument, now the guardians appear but there is no structure.

**Comment by topisani** [comment]
Ladies and gentlemen... THE BEATLES!!!
![2016-03-28_21 39 00](https://cloud.githubusercontent.com/assets/3133596/14088269/d1bf8ca4-f52e-11e5-951d-dae9a4ad88ea.png)
since #33
