### ISSUE TITLE
Chunk tiles not updating even though they are loaded

### ISSUE THREAD

**Issue by dotModded** [Team-RTG/1.9-Realistic-Terrain-Generation#118]
- [x] I am using Optifine - version: B5 pre

- Forge:1907
- RTG: 2.0.0-alpha.3

Better foliage. 

##### Issue Description:

Chuck blocks are loading however they are not visible, and periodically the game just freezes and tps goes to 0, even though it is not using any more ram or cpu usage. (Maybe make the generation multithreaded?) Also chunk loading is slowed dramatically even though the chunk has been generated.

##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Fly around
2.
3.

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by Tijeran** [comment]
I can confirm this issue, I'm having the same problem, even with latest release (RTG-1.9-2.0.0-alpha.4)

**Comment by srs-bsns** [comment]
Moving discussion to #131.
