### ISSUE TITLE
Too many ocean temples

### ISSUE THREAD

**Issue by VaiN474** [Team-RTG/1.9-Realistic-Terrain-Generation#120]
Not sure if anyone else is getting this, but it seems a bit much: [screenshot](https://dl.dropboxusercontent.com/u/80789157/2016-05-21_15.54.44.png)
world seed: -8948519052627601338

They keep on going but after about 20 of them I decided it might be a good idea to report this.

Forge: 1.9-12.16.1.1904
RTG: 1.9-2.0.0-alpha.3
not using biomes o' plenty

**Comment by topisani** [comment]
yeah we know... i forgot to remove that after some testing i did.

**Comment by VaiN474** [comment]
is it only the spacing and separation values in StructureOceanMonumentRTG?

**Comment by topisani** [comment]
yeah

**Comment by VaiN474** [comment]
Yep, that fixed it. I changed those values to match before the last commit and all is well now. Thanks.

**Comment by srs-bsns** [comment]
Fixed in https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/commit/a9ab5a94f0af6085ff6fe1fc1b6bca6b1e8ee99d
