### ISSUE TITLE
Feature Request: Custom trees

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/1.9-Realistic-Terrain-Generation#124]
Add the ability to add custom trees (via a template?) to the generation pool.

Re: [MCF \#2874](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2874)

**Comment by topisani** [comment]
i personally think this is out of scope, especially as @whichonespink44 linked a mod that did this on the MCF, and acording to him it worked pretty well. Whats @Team-RTG/everyone's thoughts?

**Comment by whichonespink44** [comment]
Yeah, it's probably out of scope. Placemod works really well and is in active development, so it's only going to get better. There might even be some integration opportunities down the line.

**Comment by srs-bsns** [comment]
I agree as well. This is something best handled by another mod, or by a possible future add-on (in which all of our custom decor can be migrated).

I mostly opened this issue for discussion, since this is something that's been requested by multiple people. (and of course I forgot the discussion label)

**Comment by srs-bsns** [comment]
It doesn't seem like we'll add this feature, atleast not anytime soon, so I'm going to close this to remove clutter.
