### ISSUE TITLE
[1.9.4] Crash with BoP

### ISSUE THREAD

**Issue by JCMais** [Team-RTG/1.9-Realistic-Terrain-Generation#126]
##### Affected Mod Versions
- Forge: 12.17.0.1954
- RTG: RTG-1.9.4-2.0.0-alpha.5
- BoP: BiomesOPlenty-1.9.4-4.1.0.2025-universal

##### Issue Description:
Crash during initial world loading.
Crash-log: https://gist.github.com/JCMais/ede876013bb190dfbc15f500a29abb60

##### Steps to reproduce the issue: (If it's easily reproducible.)
Enable ``B:"Use BOP biome layout if avaliable"=true`` in the configuration file and try to generate a new world.

![debug view](http://image.prntscr.com/image/d8a174742f3f4a53bdd25bb46b7b9c3d.png)

biome is null here: https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/dev/src/main/java/teamrtg/rtg/core/world/ChunkProviderRTG.java#L662

Edit: After more investigation, the whole ``biomes`` array is null, also, the ``biomeGenerators`` array from the ``RealisticBiomeGenerator`` class is missing all BoP biomes, see below:
![screenshot_5](https://cloud.githubusercontent.com/assets/1041647/15965695/e07143e0-2ef5-11e6-8d06-04e7e7e71d04.png)

This is an issue, because the biomes array is populated with calls to  [RealisticBiomeGenerator.getRealistic](https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/dev/src/main/java/teamrtg/rtg/api/world/gen/RealisticBiomeGenerator.java#L54)

**Comment by Zeno410** [comment]
I think this can happen if a biome is assigned to 255.

**Comment by Ezoteric** [comment]
yeah, bugger we cant enter the world for a dump... which we cant do without nei ? :P

**Comment by JCMais** [comment]
@Ezoteric there is this http://www.curseforge.com/projects/225781/

**Comment by srs-bsns** [comment]
>yeah, bugger we cant enter the world for a dump... which we cant do without nei ? :P

There is an alpha version of Mantle released for 1.9.4 which can be used to dump biome IDs with the config setting `B:"Dump BIOME ID's in log"=true`

**Comment by Ezoteric** [comment]
i do have mantle but i dont see a config :p

**Comment by srs-bsns** [comment]
`/config/SlimeKnights/Mantle.cfg`

**Comment by Ezoteric** [comment]
i dont have a slimeknight config .... weird maybe older version

**Comment by srs-bsns** [comment]
Yeah, after looking at the source, it appears they removed the dump features, all the way back in 1.8.9. Oh well.

**Comment by Ezoteric** [comment]
np :) we still got tellme ;)

**Comment by JCMais** [comment]
Here is the biome dump: https://gist.github.com/JCMais/7385b1ac1763c49c1a833e6834d5d2f5

No biome with id 255.

**Comment by topisani** [comment]
the biomeGenerators array looks normal to me on that screenshot. What should be wrong with it?

**Comment by JCMais** [comment]
@topisani I don't recall exactly where, but it tries to get the biome generator for a BOP biome from that array, but as it's not in there, Null is returned, which causes the original issue.

**Comment by srs-bsns** [comment]
Probably related: [MCF \#2968](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2968)

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#805
