### ISSUE TITLE
Stony swamps

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.9-Realistic-Terrain-Generation#127]
Original report:
http://minecraft.curseforge.com/projects/realistic-terrain-generation?comment=85

![](http://i.imgur.com/7YBeJgU.jpg)

> It seems like in RTG-1.9.4-2.0.0-alpha.5 that swamps are generating stone instead of dirt. The seed is -1854747965 and RTG is the only terrain generating mod that I'm using.

**Comment by topisani** [comment]
this is probably just some stupid surfacing mistake

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#799
