### ISSUE TITLE
Biome repair XY inversion

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.9-Realistic-Terrain-Generation#13]
It seems theres still some XY swapping going on somewhere, and i think its in biome repair code.
![2016-03-24_23.09.51.png](https://zube.io/files/Team-RTG/e78f3ec134b3fbac4626448868644304.png)

**Comment by topisani** [comment]
@Zeno410 what do you think about that?

**Comment by Zeno410** [comment]
Actually I think it's river adjustment code, which is actually legacy code. But yes, a flip.

**Comment by topisani** [comment]
sooo where would it be located?

**Comment by whichonespink44** [comment]
I suspect it might be [here](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/world/biome/realistic/vanilla/RealisticBiomeVanillaDesert.java#L154) or [here](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/world/gen/surface/vanilla/SurfaceVanillaDesert.java#L23).

The 'riverPaint' variable in the last file looks a bit suspicious, but if it's not that, then it's got to be something in one of those two files. Maybe even the SurfaceRiverOasis class itself?

**Comment by topisani** [comment]
closing all non-v2 issues, this is one
