### ISSUE TITLE
Performance Issues - Observations and Solutions

### ISSUE THREAD

**Issue by Lanse505** [Team-RTG/1.9-Realistic-Terrain-Generation#131]
##### Affected Mod Versions
- Forge: 12.17.0.1964
- RTG: RTG-1.9.4-2.0.0-alpha.5
- Pam's HarvestCraft: 1.9.4a

##### Issue Description:

Issue 1:
There are currently some rather hefty performance issues with Base RTG for 1.9.4 however it seems that with Pam's Harvestcraft this issue gets ALOT worse. 

Issue 2:
Also there seems to be a wierd bug with Chunks genning rather slowly (most likely due to chunk population) however it does cause some rather strange Visual bugs when you go into "unloaded" chunks. For example like this http://i.imgur.com/lykaoAm.png

##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Install the Above mods + JEI + WAILA (those are the only other 2 mods in this instance)
2. Load up and Create a New World
3. Use Jprofiler to check the issue or just wait 10 mins while it generates a world.

##### Extra Information:
Funnily enough this doesn't cause a crash however it drains ALOT of memory during world generation and takes about 10 minutes on my pc (which not really the best it is pretty decent)

Call Tree Information:
http://i.imgur.com/H2mRfMM.png

It continues about 70-99+ calls in and doesn't really stop, it seems to be a very very deep rabbit hole of generation calls and other wierd things.

From Discord:
Vel0cityX - Today at 9:41 PM
@zeno410 Could this be decorations requiring nearby chunks -> calling provideChunk -> decoration for these chunks happens and then it continues on like that?
The callstack suggests that this is kind of what happens right?

WhichOnesPink - Today at 9:43 PM
Zeno's delayed decoration stuff fixed that in 1.7.10... looks like we might need to port that to 1.9.4

Vel0cityX - Today at 9:43 PM
Yup, func_186025_d is provideChunk
Yeah

I'll continue digging deeper into potensial issues!

**Comment by Lanse505** [comment]
Also the chunk generation seems to be abit wonkey once it acctually generates the chunks:
http://i.imgur.com/JPePCeG.png

**Comment by Lanse505** [comment]
During Chunkgen it boils down to this call tree:
http://i.imgur.com/V1SAwqN.png

**Comment by Lanse505** [comment]
The first issue (aka massive initial generation lag) Gets even worse with BoP added :P
http://i.imgur.com/AgNclnh.png

**Comment by Lanse505** [comment]
Also adding BoP caused a crash:
https://gist.github.com/Lanse505/f0a0c4611da74d0bbdbf14229958d2fb

**Comment by Lanse505** [comment]
[22:01:42] [Server thread/INFO]: Preparing start region for level 0
[22:01:43] [Server thread/INFO]: Preparing spawn area: 0%
[22:13:09] [Server thread/INFO]: Preparing spawn area: 98%
[22:13:10] [Server thread/INFO]: Preparing spawn area: 98%

**Comment by xtraspecialj** [comment]
Any news on improving the 1.9.4 performance of this mod?  I really want to use this mod on my next playthrough but the missing pieces of chunks as mentioned in the op make it impossible.  I found a command block command to pre-generate the chunks but it takes forever just to get a decent sized radius, it isn't perfect, and I often go well outside of the radius anyways...

**Comment by srs-bsns** [comment]
@xtraspecialj, RTG is being rewritten for 1.9.4 and it is still in the early stages, hence why it is Alpha. It will be a while before it is usable for normal play.

**Comment by xtraspecialj** [comment]
@srs-bsns:. Thanks for the update sir, great mod!. I appreciate the devs hard (and beautiful) work on it. And sure, I'm aware it's in Alpha and not officially cleared to be a recommended mod for a playthrough, but you and I both know that there are many times Alpha versions are good enough to use as a "daily driver" so to speak.  Given that this is the issues thread and I hadn't seen any news other than the Discord discussion in the OP, I was just inquiring to see if the root cause had been verified and how it was going. If the update was "nope, nothing yet". Then that's cool. Or, if the update was "yep, figured it out and hopefully this problem will be solved soon" then that's even cooler.  But, the only way to know is to ask.  So I did.

**Comment by topisani** [comment]
we have been busy with the 1.7.10 release lately, but during the following weeks we should get back into 1.9.4, this time with the entire team focused on it. So nope, we havent fleshed out the specific issues, but we will start work on it pretty soon.

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#789
