### ISSUE TITLE
No default value set for option 'Top block' in section 'worldFeature.waterFeatures'

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.9-Realistic-Terrain-Generation#132]
Original report:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2946

**Comment by srs-bsns** [comment]
Possibly related to #126.

**Comment by topisani** [comment]
worldfeatures arent supposed to have a topblock, or at least they arent supposed to need to have one. the only problem is the debug message

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#791
