### ISSUE TITLE
[Bug] random patches of unfrozen ice in frozen rivers

### ISSUE THREAD

**Issue by AlphaX4** [Team-RTG/1.9-Realistic-Terrain-Generation#25]
seed: 5359449367379023817

XZ coords:   3786, 4127

![2016-03-26_17 14 08](https://cloud.githubusercontent.com/assets/18093230/14062700/9e01e0ce-f376-11e5-8712-e024ce591ee1.png)

**Comment by topisani** [comment]
this was just fixed by me, but i see you realised it was a duplicate right when you posted it. Thanks for reporting anyway!
