### ISSUE TITLE
Place BiomeGenBase biomes in RTG world

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.9-Realistic-Terrain-Generation#32]
This will allow for us to have out of the box mod compatibility. It doesnt have to be perfect, probably more like a temporary solution, but it would mean people can use RTG with small mods we dont have time to support. In a perfect world this will work perfectly, and we just have to do support for the biomes we want to change from their defaults.

**Comment by topisani** [comment]
could this be done by placing the biome normally, letting BiomeGenBase handle everything, and then get the heights around the border and smoothen the realisticBiomes next to it?

**Comment by Zeno410** [comment]
Yes, I think it could. You could write a TerrainBase that can refer to the needed vanilla data and then everything should work fine.

**Comment by topisani** [comment]
i will look at it, but its not necessarilly v2.0 stuff

**Comment by topisani** [comment]
this is in the works, seems very possible. Might work well, possibly even perfectly

**Comment by topisani** [comment]
![2016-04-06_12 01 27](https://cloud.githubusercontent.com/assets/3133596/14313200/82c8d420-fbf0-11e5-8115-279ad2c465bf.png)
Thats a BOP chappareal (or however its spelled) and its not a realisticBiomeBase version. This is working pretty well, performance impact is minimal to none
