### ISSUE TITLE
Biome support in v2

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.9-Realistic-Terrain-Generation#60]
Everything is less urgent because of rBGB (realisticBiomeGenBase) but it should still be done. BOP is probably top priority

**Comment by whichonespink44** [comment]
I'd love to do this at some point, but not gonna have any more time to spend in 2.0 until 1.7.10 is finished. So feel free to unassign me if you want to do it yourself.

**Comment by topisani** [comment]
anyone? its not very boring at all :D

**Comment by topisani** [comment]
if #64 works out as good as it looks like, there might be no need to do abyssalcraft

**Comment by whichonespink44** [comment]
How so? Won't we still need to do realistic versions of AbyssalCraft biomes?

**Comment by topisani** [comment]
nonoo, thats the point. We can put vanilla biomes in RTG worlds

**Comment by srs-bsns** [comment]
![](https://highlatencylife.files.wordpress.com/2011/11/towelie.jpg)

**Comment by whichonespink44** [comment]
> We can put vanilla biomes in RTG worlds

But they won't have realistic terrain, right? We don't want to put vanilla biomes in RTG worlds if they don't have realistic terrain. Similarly, we don't want AbyssalCraft biomes in RTG worlds if they don't have realistic terrain. Sure, if a new biome-adding mod comes along, it would be great to 'support' it with this BiomeGenBase approach, but it's only a temporary measure until we get around to creating realistic versions of the biomes.

**Comment by topisani** [comment]
Im not talking about vanilla, sorry im talking about any biome we havent created support for that uses the vanilla system. this means out of the box support for any mod. And we only have to do realistic versions of the biomes we actually want to use the time to change aesthetically.

**Comment by topisani** [comment]
I dont think we need to do Realistic versions of all biomes. most smaller mod biomes, like thaumcraft an abyssalcraft work fine in realistic worlds, especially when they also get RTG rivers and lakes, along with the biome smoothing.

**Comment by whichonespink44** [comment]
2 questions (probably obvious answers, but just want to make sure)

1. If we wanted to do just one realistic biome for AbyssalCraft, that would be fine, right? The other BGB biomes would still generate fine, correct?

2. Would it be possible to add a config option at some stage that allows the user to choose the RTG version of the biome, or the 'vanilla' version of the biome? Maybe as part of the biome config system?

**Comment by topisani** [comment]
1: yes, that is a great thing about this system, we can do biomes as we get to them, theres no need to rush into things 
2: Yes, i have planned just that

**Comment by topisani** [comment]
lol OCD

**Comment by whichonespink44** [comment]
I held off for as long as I could!! :smile:

**Comment by topisani** [comment]
quite a few other biome adding mods have been updated lately, vampirism for one.

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#797
