### ISSUE TITLE
RTG Ocean Monuments attempting to generate in Vanilla

### ISSUE THREAD

**Issue by Thiana** [Team-RTG/1.9-Realistic-Terrain-Generation#62]
Using the latest 1.9 version from curse, I keep seeing the log message " [RTG-WARN] This is not an RTG world, y u want 2 generate rtg Ocean Monuments?" when using a vanilla worldtype. 

Thanks.

**Comment by srs-bsns** [comment]
It means you've loaded RTG but you chose to create a world using the vanilla generator and not RTG. If you want to create a world using RTG you need to go into "More World Options" when you are creating a new world, and set the World Type to "Realistic".

**Comment by topisani** [comment]
but its still a bug

**Comment by srs-bsns** [comment]
It is? Well... get on it?  :cop:

**Comment by topisani** [comment]
for some reason its starting the RTG Monument generator in vanilla
Im thinking that could mean the vanilla one doesnt work

**Comment by topisani** [comment]
removing this, since its pre rewrite. If the issue arises after 2.0 is released we can reopen it
