### ISSUE TITLE
TerrainFeatures

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.9-Realistic-Terrain-Generation#63]
These will be mainly used for valcanoes for now, but the point is to have add something that is placed like a feature, with access to the distance from the center and such, but instead of directly placing blocks, it will be able to act like a biome, manipulating the terrain and surfacing.

**Comment by topisani** [comment]
this might be the solution to quite a few things, lakes and posibly rivers should be terrainFeatures as well.

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#804
