### ISSUE TITLE
Modular Surface system

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.9-Realistic-Terrain-Generation#67]
Something a bit like the decorations and terrain systems we already have going.

**Comment by Zeno410** [comment]
Yes, there are a couple of shared concerns that each generate a lot of code:
surface mixing
beach/below water/above water
rock surfacing
shadowing
mixing for the shadowing blocks.

**Comment by topisani** [comment]
this system is in, im creating a new issue for actually implementing it in all the vanilla biomes
