### ISSUE TITLE
[Question]: Channels of Communication

### ISSUE THREAD

**Issue by Lanse505** [Team-RTG/1.9-Realistic-Terrain-Generation#69]
Hello!

I'm wondering what lines of communication this team are reachable by?
I'm currently in charge of developing a 1.9 pack of sorts (will go further into detail in private) and I'm wondering how where I can reach the RTG team. (IRC, Slack, Discord, Etc)

//Best Regards
Lanse505

**Comment by Lanse505** [comment]
P.s; Sorry for the crappy English ^^'

**Comment by topisani** [comment]
Yes! the new easiest way to reach us is [HERE] (https://discord.gg/0wIG7mz3g6R7QXPi)!
