### ISSUE TITLE
Waterfalls

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.9-Realistic-Terrain-Generation#76]
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/295

This was in 1.7.10, but it's probably better suited for 1.9.

**Comment by topisani** [comment]
this might be possible with some fancy streams integration

**Comment by Zeno410** [comment]
I think waterfalls are something for Streams to do, not RTG.

**Comment by whichonespink44** [comment]
This issue was moved to Team-RTG/Realistic-Terrain-Generation#802
