### ISSUE TITLE
Deep Ocean not generating sufficiently deep

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/1.9-Realistic-Terrain-Generation#77]
As per [MCF #2342](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2342), is there a problem with Deep Ocean not generating sufficiently deep. Or, is this possibly just a rare occurance that can be ignored?

**Comment by topisani** [comment]
Yup, this is definitely a bug I have seen. But ocean monument generation has changed a bit in 1.9 anyway, so I gotta look at that

**Comment by topisani** [comment]
its not really a bug, its just the way the deep oceans are designed

**Comment by whichonespink44** [comment]
Yeah, I'd like them to be deeper, but the problem (I think) is that the depth of the oceans drags the neighbouring terrain down with it. So we had to compromise on ocean depth a bit to get around it.

**Comment by topisani** [comment]
yeah but deep ocean is alright, since there is always ocean around it

**Comment by whichonespink44** [comment]
Not always

**Comment by topisani** [comment]
goddamnint @mojang

**Comment by srs-bsns** [comment]
I don't believe this is an issue anymore.

**Comment by topisani** [comment]
how come?

**Comment by srs-bsns** [comment]
I don't believe there was ever an issue to begin with, and the last I checked there doesn't seem to be any issue with oceans.
We can always reopen this later if there is an issue.
