### ISSUE TITLE
Weird biome borders next to spawn

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.9-Realistic-Terrain-Generation#9]
Its a long line that extends on either side of a 4-8 chunks wide stripe in the middle. Terrain is smoothened, but biome border is that long line.

It might be biomerepair related, can @Zeno410 confirm or deny that?

Otherwise it might be some kind of coordinate swap somewhere.

One thing that points towards BiomeRepair, is the way it smoothens out in the end

![2016-03-24_13 43 47](https://cloud.githubusercontent.com/assets/3133596/14019077/46760188-f1d1-11e5-878a-a153d6e9f394.png)

**Comment by Zeno410** [comment]
Biome repair wouldn't be my first suspicion.. Most likely it's some variant of startup biome bugs. Earlier versions of MC generate some chunks in the init procedure for the world object, which is before any mod can modify the world object. I had a similar problem in UBC where everything in sight of spawn got generated before I could get in with an event to alter world generation. 

This is with the vanilla biome layouts, right? What are the biomes there in default?

**Comment by topisani** [comment]
yep, there are no other layouts i could use, biometweaker or CC are not updated... So i cant test BOP biomes either

**Comment by Zeno410** [comment]
Then the first question is what biomes are there "naturally". Those are "land" biomes and repair will only be putting them in if the biomes there naturally are beach or ocean. The only other possibility would be that the conversion to 1.9 created some kind of bug, like the routine not knowing what biome is there.

**Comment by topisani** [comment]
a forge update seems to have fixed this. I have no idea what the issue was, but its gone
