### ISSUE TITLE
Ocean Monument structure not spawning

### ISSUE THREAD

**Issue by topisani** [Team-RTG/1.9-Realistic-Terrain-Generation#91]
Guardians spawn, but no structure.

**Comment by BlueSteelAUS** [comment]
ty

**Comment by topisani** [comment]
This needs to be reconfirmed for the next release

**Comment by whichonespink44** [comment]
Cool, I'll check it when I generate some maps.

**Comment by BlueSteelAUS** [comment]
still not seeing them, if anyone else can please send me a seed with working underwater temples when using this mod ,

**Comment by topisani** [comment]
they might not be in the "correct" places acording to seeds and amidst, but they should be there. Have you made sure they are not disabled in the configs? also, try enabling debugging, im fairly certain it is still logging when it attempts to generate one.

Pink has seen them in 1.9, i personally haven't, but i can take a look

**Comment by BlueSteelAUS** [comment]
I've seem the mobs but not the actual temples . :(

**Comment by BlueSteelAUS** [comment]
checking configs now

**Comment by whichonespink44** [comment]
![2016-05-09_08 34 04](https://cloud.githubusercontent.com/assets/10927161/15106419/1acba6b4-15c1-11e6-904d-7bcc28940eb8.png)

World Seed=4595937241009089821

@BlueSteelAUS I'm going to close this, but if they're still not generating for you, please let us know and we'll look into it further.
