### ISSUE TITLE
PMP biome support

### ISSUE THREAD

**Issue by Tijeran** [Team-RTG/1.9-Realistic-Terrain-Generation#92]
Is it possible to add support for the Plant Mega Pack mod? when using both RTG, PMP and biomes of plenty I get this error:

http://paste.ee/p/iE7ZK

- OptiFine Version: OptiFine_1.9_HD_U_B1
- Forge: 1.9-12.16.0.1867  
- RTG: 1.9-0.0.5
- BiomesOPlenty 4.0.0.2000

The game seems to load and run smooth for a while, but when I enter certain biomes it crash all of a sudden with that report, where I guess the problem may be a biome conflict...

**Comment by srs-bsns** [comment]
That release of RTG is alpha and was built with Forge 12.16.0.1830. It won't work properly with newer Forge.

We should have a newer release out soon.
