### ISSUE TITLE
Biome support for Plant Mega Pack

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.9-Realistic-Terrain-Generation#93]
#92

Wasn't aware that PMP for 1.9 had biomes, but it looks like it does. Yay! :dancer:

**Comment by srs-bsns** [comment]
Nothing on the PMP site suggests there are biomes.

I assume what you are seeing in that stacktrace is a utility class to get info about an existing biome so that PMP knows what plants to decorate the biome with.

**Comment by whichonespink44** [comment]
Ah yes, that's what prompted this.

Ah well, one less thing to do! :)
